### PR TITLE
Update schemas

### PR DESCRIPTION
**Pull request by smbea**

### CODE REVIEW

**Comment by smbea** [comment]
@marstamm @philippfromme could I get an approval here? Then I could make https://github.com/bpmn-io/bpmn-js-element-templates/pull/14 ready for review before my FTO 🙂

**Comment by marstamm** [comment]
Should we add a test case/expand existing test cases for this feature? (e.g. make one of the options optional: https://github.com/bpmn-io/element-templates-validator/blob/main/test/fixtures/multiple-connectors.json#L39)

**Comment by smbea** [comment]
@marstamm I added tests for it

**Review by marstamm — APPROVED** [review]
🚀

**Pull request merged**
