### PR TITLE
Add feel validation

### PR DESCRIPTION
**Pull request by marstamm**
related to https://github.com/bpmn-io/bpmn-js-properties-panel/pull/602

### CODE REVIEW

**Comment by marstamm** [comment]
This repo does not grant write access to bpmn.io members ( /cc @MaxTru )

**Comment by marstamm** [comment]
Yes, works now :+1:

**Review by pinussilvestrus — APPROVED** [review]
LGTM

**Comment by marstamm** [comment]
Thanks for the quick follow-up :smile:

**Pull request merged**
