### PR TITLE
chore(build): create standalone validator during install

### PR DESCRIPTION
**Pull request by marstamm**
- published files will be bundled but not standalone
- standalone validator is created in `postinstall` script, using the schema version available to npm

### CODE REVIEW

**Comment by nikku** [comment]
Not sure if `postinstall` helps us here. 

From what I understand we'd need to re-build the validator every time we update a schema:

```
install validator <-- build schema
update schema <-- does validator#postinstall pick this up?
```

Another one to think about: Does building the schema require development dependencies? And how does it affect our build times.

The alternative is to keep our existing strategy, but ensure that renovate and friends are appropriately configured and so forth.

**Comment by marstamm** [comment]
> From what I understand we'd need to re-build the validator every time we update a schema:

I have not thought about it initially, but played around with scripts locally a bit. `postinstall` scripts are run again when subtree dependency modifications happens. I did find some forum entries confirming this, but no primary source so I validated this locally:

```sh
% NPM_CONFIG_REGISTRY=http://localhost:4873 npm update nested --verbose
npm verb cli /home/stamm/.nvm/versions/node/v16.13.1/bin/node /home/stamm/.nvm/versions/node/v16.13.1/bin/npm
[...]
npm info run child@1.0.0 postinstall ../child echo "postinstall in child called"
npm info run child@1.0.0 postinstall { code: 0, signal: null }
npm timing build:run:postinstall:../child Completed in 11ms
[...]
```

So while the current implementation would not update it (as it overrides the source file), it is possible to update to the latest version after an `update` commands with a postinstall script

> Does building the schema require development dependencies

No, as the bundeling is already done during the build step, creating the standalone version only requires `ajv` (prod dependency) and node internals like fs.

> And how does it affect our build times.

It adds ~350ms to the install time for downstream libraries

**Comment by marstamm** [comment]
One thing I'm not certain of before this is ready for review: 

with [a36bbf6](https://github.com/bpmn-io/element-templates-validator/pull/15/commits/a36bbf649ae819f5272afd9a8626c2dff40d25ba) we could make the schema versions a peer dependency, so the integrating library can chooses the schema version explicitly. Con: we need both C7 and Zeebe schemas even if the downstream library only uses one of those, which is rather unexpected.

Alternatives:
- Have the schema version as a normal dependency, updates can be done through `npm update` on the downstream lib.
We would still need to release update for this lib for breaking changes in the schema repo.

- Refactor the code to work with missing dependencies (e.g. don't build the validator if schema is not provided) using [peerDependenciesMeta](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta). This would also allow this library to be installed without any schemas without error, which would be unexpected when the code then fails when you try to validate it.

**Comment by nikku** [comment]
I'm a fan of this:

> Have the schema version as a normal dependency, updates can be done through npm update on the downstream lib.
We would still need to release update for this lib for breaking changes in the schema repo.

Did you validate with https://github.com/bpmn-io/element-templates-validator/pull/15#issuecomment-1415617946 that a upstream dependency update rebuilds things in this library:

```
element-templates-validator
  - actual-schema <--- UPDATE
```

**Comment by marstamm** [comment]
I verified earlier that postinstall scripts are called in this structure:
```
root
  - child <== postinstall run again
     - nested <== update
```

I also validated again with
```
root
  - @bpmn-io/element-templates-validator <== postinstall run again
     - @camunda/zeebe-element-templates-json-schema <== update
```
with the same result.

Note: I did not test this against the actual npm registry but on a local registry. On monday, I might try with some test packages tags on the npm registry to verify it actually works. The generated manifests can have influence on the install scripts being run.

**Comment by marstamm** [comment]
Unfortunately, it seems that the behavior is different when the package is loaded from the actuall npm registry 😞

It does not run the postinstall script when the package was already installed, so this is not a viable method of solving the problem. You would have to delete `node_modules` and reinstall everything to get the desired result. I don't know why it behaves different locally

Guess we have to stick with bundeling for now

**Pull request closed without merging**
